apiVersion: v1
kind: Pod
metadata:
    name: master-nginx
    labels: 
       app: master-nginx
spec:
   containers:
   - name: master-nginx
     image: hr1daya/cloudethix_master_nginx_kiran:master
     ports:
     - containerPort: 80
